### ISSUE TITLE
[ Feature | SendTimestamps ] Localized date/time selection

### ISSUE THREAD

**Issue by Wiethoofd** [Taimoor-Tariq/BetterDiscordStuff#17]
The popup when selecting a date & time to send it shows US format styled date & time values instead of being localized to the system localization.
![SendTimeStamps](https://user-images.githubusercontent.com/9917564/158507333-aef786f5-5309-4c82-a47e-a35f5a4ce0dc.png)
An option in the settings to show date when selecting it as DD-MM-YYYY or basing it off system user locale would be appreciated, similar for the time to be displayed and selected in the 24h format.

**Comment by Taimoor-Tariq** [comment]
Thank you for suggesting this feature.
I will look into it over the next week.

**Comment by Taimoor-Tariq** [comment]
So I looked into setting formats for Date and Time inputs, doing what you've asked for requires me to rewrite the plugin since I can't really do it using the way I have currently written the plugin. I will be rewriting the plugin in the near future anyway so I will keep this in mind while writing it 🙂.
