### ISSUE TITLE
[ BUG | SendTimestamps ] Nothing happens after clicking on "Enter"

### ISSUE THREAD

**Issue by RBXFFW** [Taimoor-Tariq/BetterDiscordStuff#19]
https://user-images.githubusercontent.com/51197551/159168023-f7418803-888a-4074-a156-866f3d1e8482.mp4

**Comment by LewsTherinTelescope** [comment]
Are you using the Slate v2 Canary builds? Those broke most plugins affecting the chat box for me, and that's about what it looks like when I try to use this on it.

**Comment by RBXFFW** [comment]
Canary 122119 (bc537af)
BetterDiscord 1.5.2
Host 1.0.45 Windows 10 64-Bit (10.0.22000)

Still not working on these Versions,

Sorry for late answer

**Comment by aaronliu0130** [comment]
I can reproduce on the latest stable on win11 using plugin version 1.1.9 and the latest betterdiscord version.

**Comment by xartuu** [comment]
I have the same problem, below are the versions I am using.

> SendTimestamps v1.1.9
Stable 122087 (5c6d04c)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

The problem lies in inserting text into a text field.
In the [screenshot](https://i.imgur.com/VJdWdN2.png) I am posting the error from the console.

**I leave the solution to the problem for @Taimoor-Tariq (the plugin author) below.**
https://github.com/QWERTxD/BetterDiscordPlugins/commit/faf3ac23848d121b8a8501aab6df2c9434da1e3a#diff-591d38e3dc72e1aa6dc2885ba084332155a5915afb79b3f89dfdab0f1911b0f2R204

**Comment by Taimoor-Tariq** [comment]
Sorry been busy with university stuff.
I will fix it soon.

**Comment by Taimoor-Tariq** [comment]
Fixed in the latest update 🙂

**Comment by aaronliu0130** [comment]
> Fixed in the latest update 🙂

The update didn't deploy for me. It also seems like you removed the @updateURL link in the source?

So do I have to resort to downloading manually?

**Comment by Taimoor-Tariq** [comment]
> > Fixed in the latest update 🙂
> 
> The update didn't deploy for me. It also seems like you removed the @updateURL link in the source?
> 
> So do I have to resort to downloading manually?

I removed the ` @updateURL` since it is no longer required by BD and the plugin uses the `github_raw` to update plugins now.
If you still haven't received an update, try turning the plugin off and on again. If it still does not work, then just re-download the plugin by clicking [here](https://www.taimoor.me/api/bd/SendTimestamps.plugin)
