### ISSUE TITLE
[ BUG | (SendTimestamps) - BD says it's "Outdated".  What does that mean?

### ISSUE THREAD

**Issue by rexkix** [Taimoor-Tariq/BetterDiscordStuff#35]
**Issue**
Better Discord says the plugin is Outdated?  I hope that doesn't mean you've given up on it.  I'm scared to delete it, lest I won't be able to get it back, but maybe that's the right thing to do.  Delete it, then reinstall it, and everything is okay?

**Comment by Taimoor-Tariq** [comment]
This happens when my plugin is a version ahead of the Official BD Plugin Directory. It takes a few days for the version to update in the Official Directory. Don't worry and just ignore the message if you already have version 2.1.6.

My plugin version: v2.1.6
The version in the Official Directory: v2.1.5

**Comment by rexkix** [comment]
As it happens, I was on 2.1.4 for some reason.  I deleted and resubscribed and everything seems fine now.  As far as I'm concerned, you may close this.  Thank you.
